### ISSUE TITLE
Sim gets stuck on maximum rotations

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/trig-tour#61] opened 2015-10-21 17:12 UTC
device: Tycho iPad 2

Operating System: iOS 9.0

Browser: Safari

Problem description: If you bring to the sim to maximum rotations (I did this by dragging around the unit circle) the dizzy girl appears and then you can't go backwards. The girl stays on the screen and the point will only move about halfway around the circle before it stops. 

Steps to reproduce: drag around unit circle until max rotations is reached and girl appears (I did this quickly, it may be dependent on speed). Attempt to reduce rotations. 

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12610678/10644194/8b2adef0-77e4-11e5-8e35-ee9616e4f448.png)
This is where it will not let me go backwards.

Troubleshooting information (do not edit):
Name: ‪Trig Tour‬
URL: http://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.0-dev.18/trig-tour_en.html
Version: 1.0.0-dev.18 2015-10-15 01:02:12 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_0 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A344 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"e2237347","branch":"master"},"babel":{"sha":"931afbf1","branch":"master"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"157b9cf3","branch":"master"},"dot":{"sha":"d99cbe46","branch":"master"},"joist":{"sha":"121bb0de","branch":"master"},"kite":{"sha":"40dc703a","branch":"master"},"phet-core":{"sha":"e9f36af1","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"c1d6232d","branch":"master"},"scenery-phet":{"sha":"88ade507","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"b66398a5","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"},"trig-tour":{"sha":"00c1618a","branch":"master"}}

**Comment by elisemorgan** [comment] 2015-10-21 17:13
This behavior was not observed in Windows or Mac

**Comment by jessegreenberg** [comment] 2015-10-27 23:24
I am unable to reproduce this issue on iPad2 iOS 8.2, regardless of the rotation speed.  I will see if I can verify the issue on the Tycho iPad2 device.

**Comment by jessegreenberg** [comment] 2015-11-23 19:07
The clipping shape of the SpiralNode is not being updated until theta is dragged below the max angle for the sim, so it feels like the sim is getting stuck.  Theta should not be allowed to grow beyond the max angle, but the shape should still be updated if dragged such that it decreases the absolute value of theta.  Will commit a fix for this soon.

**Comment by jessegreenberg** [comment] 2015-12-31 00:43
Fixed in the commit above.  The spiral shape and indicator arrows will update even if the angle is larger than the max allowed angle.  The unit circle no longer feels stuck after dragging beyond the largest angle.  Closing.

**Closed by jessegreenberg** 2015-12-31 00:43 UTC
